apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: cart
  labels:
    tier: app
    project: roboshop
    service: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
      project: roboshop
      service: cart
  template:
    metadata:
      labels:
        tier: app
        project: roboshop
        service: cart
    spec:
      containers:
      - image: saivinaylt/cart:v1
        imagePullPolicy: Always
        name: cart
---
kind: Service
apiVersion: v1
metadata:
  namespace: roboshop
  name: cart
  labels:
    tier: app
    project: roboshop
    service: cart
spec:
  selector:
    tier: app
    project: roboshop
    service: cart
  ports:
  - name: cart-port
    protocol: TCP
    port: 8080
    targetPort: 8080



