apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: shipping
  labels:
    service: shipping
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:  
      service: shipping
      tier: app
  template:
    metadata:
      labels:
        service: shipping
        tier: app
    spec:
      containers:
      - image: saivinaylt/shipping:v1
        imagePullPolicy: Always
        name: shipping
---
kind: Service
apiVersion: v1
metadata: 
  namespace: roboshop
  name: shipping
  labels:
    service: shipping
    tier: app
spec:
  selector:
    service: shipping
    tier: app
  ports:
  - name: shipping-port
    protocol: TCP
    port: 8080
    targetPort: 8080
    


