kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: roboshop
  name: ratings
  labels:
    service: ratings
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ratings
      tier: app
      project: roboshop
  template:
    metadata:
      labels:
        service: ratings
        tier: app
        project: roboshop
    spec:
      containers:
      - image: saivinatlt/ratings:v1
        name: ratings
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  namespace: roboshop
  name: ratings
  labels:
    service: ratings
    tier: app
    project: roboshop
spec:
  selector:
    service: ratings
    tier: app
    project: roboshop
  ports:
  - name: ratings-port
    protocol: TCP
    port: 80
    targetPort: 80




