kind: ConfigMap
apiVersion: v1
metadata:
  namespace: roboshop
  name: mysql-configmap
data:
  MYSQL_ALLOW_EMPTY_PASSWORD : "yes"
  MYSQL_DATABASE : cities
  MYSQL_USER : shipping
  MYSQL_PASSWORD : secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: mysql
  labels:
    tier: db
    service: mysql
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
      service: mysql
      project: roboshop
  template:
    metadata:
      labels: 
        tier: db
        service: mysql
        project: roboshop
    spec:
      containers:
      - image: saivinaylt/mysql:v1
        imagePullPolicy: Always
        name: mysql
        envFrom:
        - configMapRef:
            name: mysql-configmap 
---
kind: Service
apiVersion: v1
metadata: 
  namespace: roboshop
  name: mysql
  labels:
    tier: db
    service: mysql
    project: roboshop
spec:
  selector:
    tier: db
    service: mysql
    project: roboshop
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306
    

