apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: user
  labels: 
    service: user
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user
      tier: app
      project: roboshop
  template:
    metadata:
      labels:
        service: user
        tier: app
        project: roboshop
    spec:
      containers: 
      - image: saivinaylt/user:v1
        imagePullPolicy: Always
        name: user
---
kind: Service
apiVersion: v1
metadata:
  namespace: roboshop
  name: user
  labels:
    service: user
    tier: app
    project: roboshop
spec:
  selector:
    service: user
    tier: app
    project: roboshop
  ports:
  - name: user-port
    protocol: TCP
    port: 8080
    targetPort: 8080

