apiVersion: apps/v1
kind: Deployement
metedata:
  name: redis
  labels: 
    tier: db
    service: redis
spec: 
  replicas: 1
  selector:
    matchLabels:
      tier: db
      service: redis
  template:
    metedata:
      labels:
        tier: db
        service: redis
